# Workflow to automatically lint gdscript code
name: gdlint on push

on:
  push

jobs:
  gdlint:
    name: gdlint scripts
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Ensure python is installed
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install gdtoolkit
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install 'gdtoolkit==4.*'

      # Lint the godot-xr-tools addon
      - name: Linter
        run: |
          error_found=0  # Initialize a flag to track errors
  
          for file in $(find . -type f -name "*.gd" -not -path "./faster-than-scrap/addons/*"); do
              echo "Processing $file"
              if ! gdlint "$file"; then
                  echo "Error in $file"
                  error_found=1  # Set the flag if gdlint fails
              fi
          done
          
          if [ $error_found -ne 0 ]; then
              echo "Linting completed with errors."
              exit 1  # Exit with failure if any errors were found
          else
              echo "All files passed linting."
              exit 0  # Exit with success if no errors were found
          fi
  directory:
    name: check directory case name
    runs-on: ubuntu-latest
          
    steps:
      # Check out the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Lint the godot-xr-tools addon
      - name: Check directories names
        run: |
          all_fine=True

          for dir_path in $(find . -type d); do
            dir_name=$(basename $dir_path)
            if [[ $dir_name =~ [A-Z] ]] then
              echo "Directory on path: ${dir_path} contains capital letters"
              all_fine=False
            fi
          done

          if [[ $all_fine = False ]] ; then
              echo "Found wrongly named directory"
              exit 1
          fi

          exit 0